name: "Concourse CI Cluster"
description: |
  Concourse CI Cluster version with spreaded workers
version: 3.13.0.2
category: Applications
maintainer: "Eugen Mayer <eugen.mayer@kontextwork.de>"
projectURL: http://concourse.ci/
