name: "Concourse CI Cluster"
description: |
  Concourse CI Cluster version with spreaded workers
version: 3.14.1.0
category: Applications
maintainer: "Eugen Mayer <eugen.mayer@kontextwork.de>"
projectURL: http://concourse.ci/
