version: "2"

services:
  jira:
    image: eugenmayer/jira:${JIRA_VERSION}
    labels:
{{- if .Values.EXTRA_LABELS }}
{{.Values.EXTRA_LABELS | indent 6}}
{{- end}}
      traefik.enable: true
      traefik.port: 8080
      traefik.frontend.rule: ${TRAEFIK_FRONTEND_RULE}
      traefik.acme: ${TRAEFIK_FRONTEND_HTTPS_ENABLE}
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent.role: 'environment'
    volumes:
      - jira_data:/var/atlassian/jira
    environment:
      JIRA_DELAYED_START: 10
      JIRA_DATABASE_URL: "postgresql://${JIRA_DB_USER}@db/${JIRA_DB_NAME}"
      JIRA_DB_PASSWORD: ${DB_PASSWORD}
      CATALINA_OPTS: ${CATALINA_OPTS}
{{- if eq .Values.USE_PROXY "true" }}
      JIRA_PROXY_NAME: ${JIRA_PROXY_DOMAIN}
      JIRA_PROXY_PORT: ${JIRA_PROXY_PORT}
      JIRA_PROXY_SCHEME: ${JIRA_PROXY_SCHEME}
{{- end }}
{{- if eq .Values.USE_EXTERNAL_DB_SERVICE "true" }}
    external_links:
      - ${EXTERNAL_DB_SERVICE}:db
{{- end }}

{{- if eq .Values.USE_EXTERNAL_DB_SERVICE "false" }}
  db:
    image: postgres:9.6
    volumes:
      - jira_db:/var/lib/postgresql
    environment:
      POSTGRES_DB: ${JIRA_DB_NAME}
      POSTGRES_USER: ${JIRA_DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
{{- end }}
volumes:
  jira_data:
    driver: local
  jira_db:
    driver: local
