version: "2"

services:
  confluence:
    image: eugenmayer/confluence:7.5.0
    labels:
{{- if .Values.EXTRA_LABELS }}
{{.Values.EXTRA_LABELS | indent 6}}
{{- end}}
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent.role: 'environment'
      traefik.enable: true
      traefik.port: 8090
      traefik.frontend.rule: ${TRAEFIK_FRONTEND_RULE}
      traefik.acme: ${TRAEFIK_FRONTEND_HTTPS_ENABLE}
    environment:
      CATALINA_OPTS: ${CATALINA_OPTS}
{{- if eq .Values.USE_PROXY "true" }}
      CONFLUENCE_PROXY_NAME: ${CONFLUENCE_PROXY_NAME}
      CONFLUENCE_PROXY_PORT: ${CONFLUENCE_PROXY_PORT}
      CONFLUENCE_PROXY_SCHEME: ${CONFLUENCE_PROXY_SCHEME}
      CONFLUENCE_DB_HOST: db
      CONFLUENCE_DB_PORT: 5432
{{- end }}
    volumes:
      - confluence_data:/var/atlassian/confluence
{{- if eq .Values.USE_EXTERNAL_DB_SERVICE "true" }}
    external_links:
      - ${EXTERNAL_DB_SERVICE}:db
{{- end }}

{{- if eq .Values.USE_EXTERNAL_DB_SERVICE "false" }}
  db:
    image: blacklabelops/postgres:9.4.9
    volumes:
      - confluence_db:/var/lib/postgresql
    environment:
      POSTGRES_DB: ${CONFLUENCEDB_NAME}
      POSTGRES_USER: ${CONFLUENCEDB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_ENCODING: "UNICODE"
      POSTGRES_COLLATE: "C"
      POSTGRES_COLLATE_TYPE: "C"
{{- end }}
volumes:
  confluence_data:
    driver: local
  confluence_db:
    driver: local
