name: "Rundeck"
description: |
  Rundeck a remote task runner http://rundeck.org/
version: 2.11.3.1
category: Applications
maintainer: "Eugen Mayer <eugen.mayer@kontextwork.de>"
projectURL: http://rundeck.org/
