name: "Rundeck"
description: |
  Rundeck a remote task runner http://rundeck.org/
version: 3.0.7.0
category: Applications
maintainer: "Eugen Mayer <eugen.mayer@kontextwork.de>"
projectURL: http://rundeck.org/
