name: "Atlassian JIRA"
description: |
  Atlassian Jira
version: 7.4.4.0
category: Applications
maintainer: "Eugen Mayer <eugen.mayer@kontextwork.de>"
projectURL: https://de.atlassian.com/software/jira
