rubygems:
  image: eugenmayer/geminabox:latest
  environment:
    ADMINUSERNAME: ${ADMINUSER}
    ADMINPASSWORD: ${ADMINPASSWORD}
    READERUSERNAME: ${READERUSER}
    READERPASSWORD: ${READERPASSWORD}
    READ_AUTH: ${READ_AUTH}
    LDAP_HOST: ${LDAP_HOST}
    LDAP_PORT: ${LDAP_PORT}
    LDAP_ENCRYPTION: ${LDAP_ENCRYPTION}
    LDAP_BASE: ${LDAP_BASE}
    LDAP_USER_ID: ${LDAP_USER_ID}
  volumes:
    - ${DATA}:/geminabox/data
  tty: true
  stdin_open: true
  labels:
    io.rancher.container.create_agent: 'true'
    io.rancher.container.agent.role: 'environment'
