apacheds:
  image: eugenmayer/apacheds:2.0.0-m24
  environment:
    DS_HOST: ${DS_HOST}
    DS_SASL_HOST: ${DS_SASL_HOST}
    DS_SASL_REALM: ${DS_SASL_REALM}
    DS_SASL_DOMAIN: ${DS_SASL_DOMAIN}
    DS_SASL_BASEDN: ${DS_SASL_BASEDN}
    DS_KRB_REALM: ${DS_KRB_REALM}
    DS_KRB_BASEDN: ${DS_KRB_BASEDN}
    DS_KEYSTORE_PATH: /bootstrap/apacheds.keystore
    DATAPATH: ${DATAPATH}
    BOOTSTRAPPATH: ${BOOTSTRAPPATH}
    CERTSTOREPATH: ${CERTSTOREPATH}
    CONFPATH: ${CONFPATH}
    DS_KEYSTORE_PATH: "/bootstrap/apacheds.keystore"
  volumes:
    - ${DATAPATH}:/data
    - ${BOOTSTRAPPATH}:/bootstrap
    - ${CERTSTOREPATH}:/certs
    - ${CONFPATH}:/conf
  labels:
    io.rancher.container.create_agent: 'true'
    io.rancher.container.agent.role: 'environment'
