name: "Atlassian Bitbucket Server"
description: |
  Atlassian Bitbucket Server
version: 5.10.0.2
category: Applications
maintainer: "Eugen Mayer <eugen.mayer@kontextwork.de>"
projectURL: https://de.atlassian.com/software/bitbucket
