name: "Sona-nexus registry"
description: |
  Docker-registry, npm, java and ruby server with permissions and authentication backend
version: 0.0.4
category: Applications
maintainer: "Eugen Mayer <eugen.mayer@kontextwork.de>"
projectURL: https://www.sonatype.com/nexus-repository-oss