name: "Sona-nexus registry"
description: |
  Docker-registry, npm, java and ruby server with permissions and authentication backend
version: 3.3.2.0
category: Applications
maintainer: "Eugen Mayer <eugen.mayer@kontextwork.de>"
projectURL: https://www.sonatype.com/nexus-repository-oss
